### ISSUE TITLE
FTL research for IR3 requires all packs

### ISSUE THREAD

**Issue by Sipke82** [elmodor/factorio-space-extension#1]
The earlier FTL researches requires all science packs, where i think the first one should only show a few?

![image](https://github.com/elmodor/factorio-space-extension/assets/30873812/04a184df-e864-409a-8972-60d5225f4d59)

**Comment by elmodor** [comment]
If you compare it to the original Space Extension, yes. The FTL research there required fewer packs.

However, I personally found it a bit strange that, so far in the game, the tech would require only the basic science packs. I therefore changed it to require more of them but drastically reduced the amount of packs needed for each research tier. So that in the end it shouldn't make much of a difference. Especially with the newly added stage where you need to ramp up the production anyways.

I've tested this in vanilla and a few other modpacks, not with IR3 tho.
Is it too step for IR3 packs?
Would it be better to reduce the amount needed in IR3 or actually remove some science packs?

There's also a startup option for a "classic mode" which reverts these FTL changes back to the original behavior but also removes the new last stage I added.

**Comment by Sipke82** [comment]
Ah I see your reasoning. To start, I like the new final stage. But I also
liked that in the previous space extension the FTL research would start
with only 1 and then 2 and then 3 etc. packs.
Because when going for these final researches, you are faced with the fact
that your current base for example would only allow for like 100 SPM while
you will need 1000 SPM to make it bearable. So I go out to make new Sub
Factories per pack to supply 1000 SPM. And thus I will start building the
red pack one, which is done quickly, and i could start using this 1000 SPM
straight away, because the first FTL would only need red packs. Then I will
start building the second sub factory, which I can then use.. etc etc.

So in the current scenario, I've already built 3 sub factories, but they
are not yet activated, because all the FTL researches needs 5 packs...

To conclude, the ramping up of the packs needed, allowed for early use of
sub factories and to see if everything is working properly before moving on
to the next subfactory. It felt like a more gradual experience.  So perhaps
what is needed is to split up the classic mode option, to allow the final
stage, but with the classic FTL costs.

**Comment by elmodor** [comment]
Thanks! And yeah that makes sense.

Now I have to think which mode should be default, hah.

I will def. add a setting for this.

**Comment by elmodor** [comment]
I set this as the new default behavior because, as you mentioned, it makes more sense if you are in the process of ramping up the science production to have something to research in the meantime. 

Added a startup setting to include all science packs for all FTL researches tho.

**Comment by Sipke82** [comment]
Awesome, thanks for the lightning fast update!

**Comment by Sipke82** [comment]
sorry to bother you again. i would like to point out that the information
page on the mod portal should also reflect this change?

Again thanks, i'm really enjoying this mod.

**Comment by elmodor** [comment]
Sorry for the late reply, I had added the changes to the [changelog](https://mods.factorio.com/mod/SpaceModFeorasFork/changelog) as well as added following line to the main mod page:
`Ability to use all science packs for FTL research (see startup settings)`
Do you think there should be added something else/more?

Glad you are enjoying it!

**Comment by Sipke82** [comment]
Well im nearing the finish line, the last research is a stretch, as it should be. :-) This is how my IR3 base is looking now:

![image](https://github.com/elmodor/factorio-space-extension/assets/30873812/089d95f3-94d0-4c32-8a68-9c1cce9856b7)

**Comment by elmodor** [comment]
Looking good! Well done
